apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "testuser" to read pods in the "kube-system" namespace.
kind: ClusterRoleBinding
metadata:
  name: naresh-the-cluster-admin-Binding
subjects:
- kind: User 
  name: naresh # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
