apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-readonly-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods","services", "persistentvolumes", "nodes" "deployments", "replicasets"]
  verbs: ["get", "watch", "list", "describe"]
  #verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
