apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "testuser" to read pods in the "kube-system" namespace.
kind: RoleBinding
metadata:
  name: prod-ns-readonly-rolebinding
  namespace: prod 
subjects:
- kind: User
  name: testuser # Name is case sensitive
  namespace: prod
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: prod-ns-readonly-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
