apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
#  tolerations:
#  - key: covid 
#    operator: "Exists"
#    effect: "NoExecute"
#   - key: covid
#     operator: "Equal"
#     value: "true"
#     effect: "NoSchedule"


#    operator: "Exists"/"Equal"
#    effect: "NoSchedule"/"PreferNoSchedule"/"NoExecute"
