apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-netpolicy
spec:
  podSelector:
    matchLabels:
      app: kubeserve
  ingress:      
  - from:
    - podSelector:
        matchLabels:
          app: myapp
          #    ports:
          #    - port: 80 
