apiVersion: v1
kind: Pod
metadata:
  name: nginxlogs-pod
spec:
  containers:
   - name: test-container
     image: nginx 
     volumeMounts:
      - name: nginxlogs
        mountPath: /var/log/nginx 
  volumes:
   - name: nginxlogs
     hostPath:
       path: /tmp/nginxlogs     # directory location on host
       type: Directory  # this field is optional
