kind: Pod
apiVersion: v1
metadata: 
  name: initpod
  labels:
    app: debitcarapp
spec:
  containers: 
    - name: debitcardcont
      image: tomcat
      ports: 
        - containerPort: 8080
  initContainers:
    - name: validatelogin
      image: alpine
      command: ["sh", "-c", "sleep 60"]
    - name: validatedb
      image: ubuntu
      command: ["bash", "-c", "sleep 30"]
      
