kind: ReplicationController 
apiVersion: v1   ## kubectl explain ReplicaSet
metadata:
  namespace: prod
  name: myrc
spec:
  selector:
     app: web
  replicas: 3
  template: 
    metadata:
      name: mypod
      labels: 
        app: web
    spec:
      containers:
       - name: cont1
         image: tomcat
         ports:
          - containerPort: 8080
